package org.vtiger.contacts;

import java.io.IOException;
import org.apache.poi.EncryptedDocumentException;
import org.testng.Assert;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;
import org.vtiger.businessutility.BaseClass;
import org.vtiger.objectrepository.ContactsPage;
import org.vtiger.objectrepository.CreateContactsPage;
import org.vtiger.objectrepository.Homepage;
@Listeners(org.vtiger.genericutility.ListenerUtility.class)
public class TC002_ToVerifyUserIsAbleToCreateContactWithAllFieldsTest extends BaseClass{
@Test(retryAnalyzer = org.vtiger.genericutility.RetryAnalyzer.class)
public void toCreateContactsWithAllFields() throws EncryptedDocumentException, IOException, InterruptedException {
	String FIRSTNAME= futil.readDataFromExcelFile("ContactPage", 1, 0)+jUtil.randomData();
	String LASTNAME= futil.readDataFromExcelFile("ContactPage", 1, 1)+jUtil.randomData();
	String TITLE=futil.readDataFromExcelFile("ContactPage", 1, 2);
	String DEPARTMENT=futil.readDataFromExcelFile("ContactPage", 1, 3);
	String EMAIL=futil.readDataFromExcelFile("ContactPage", 1, 4);
	String ASSISTANT=futil.readDataFromExcelFile("ContactPage", 1, 5);
	String ASSISTANTPHONE=futil.readDataFromExcelFile("ContactPage", 1, 6)+jUtil.randomNumber(100000);
	String OFFICEPHONE=futil.readDataFromExcelFile("ContactPage", 1, 7)+jUtil.randomNumber(100000);
	String MOBILE=futil.readDataFromExcelFile("ContactPage", 1, 8)+jUtil.randomNumber(100000);
	String HOMEMOBILE= futil.readDataFromExcelFile("ContactPage", 1, 9)+jUtil.randomNumber(100000);
	String OTHERPHONE=futil.readDataFromExcelFile("ContactPage", 1, 10)+jUtil.randomNumber(100000);
	String FAX=futil.readDataFromExcelFile("ContactPage", 1, 11)+jUtil.randomNumber(100000);
	String BIRTHDATE=futil.readDataFromExcelFile("ContactPage", 1, 12);
	String SECONDARYEMAIL=futil.readDataFromExcelFile("ContactPage", 1, 13);
	String SUPPORTSTARTDATE=futil.readDataFromExcelFile("ContactPage", 1, 14);
	String SUPPORTENDDATE=futil.readDataFromExcelFile("ContactPage", 1, 15);
	String MAILINGSTREET=futil.readDataFromExcelFile("ContactPage", 1, 16)+jUtil.randomData()+ " street";
	String MAILINGPOBOX=futil.readDataFromExcelFile("ContactPage", 1, 17);
	String MAILINGCITY=futil.readDataFromExcelFile("ContactPage", 1, 18);
	String MAILINGSTATE=futil.readDataFromExcelFile("ContactPage", 1, 19);
	String MAILINGPOSTALCODE=futil.readDataFromExcelFile("ContactPage", 1, 20);
	String MAILINGCOUNTRY=futil.readDataFromExcelFile("ContactPage", 1, 21);
	String OTHERSTREET=futil.readDataFromExcelFile("ContactPage", 1, 22)+jUtil.randomData()+" street";
	String OTHERPOBOX=futil.readDataFromExcelFile("ContactPage", 1, 23);
	String OTHERCITY=futil.readDataFromExcelFile("ContactPage", 1, 24);
	String OTHERSTATE=futil.readDataFromExcelFile("ContactPage", 1, 25);
	String OTHERPOSTALCODE=futil.readDataFromExcelFile("ContactPage", 1, 26);
	String OTHERCOUNTRY=futil.readDataFromExcelFile("ContactPage", 1, 27);
	String DESCRIPTION=futil.readDataFromExcelFile("ContactPage", 1, 28);
	Homepage homepage=new Homepage(driver);
	homepage.getContactsLink().click();
	ContactsPage contactPage= new ContactsPage(driver);
	contactPage.getCreateContactsButton().click();
	CreateContactsPage createContactPage= new CreateContactsPage(driver);
	webUtil.toSelectByIndex(createContactPage.getSalutationTypeDropdown(), 1);
	createContactPage.getFirstNameTextFiled().sendKeys(FIRSTNAME);
	createContactPage.getLastNameTextFiled().sendKeys(LASTNAME);
	createContactPage.getOfficePhoneTextField().sendKeys(OFFICEPHONE);
	createContactPage.getMobileTextField().sendKeys(MOBILE);
	webUtil.toSelectByValue(createContactPage.getLeadsourceDropdown(),"Self Generated");
	createContactPage.getHomePhoneTextField().sendKeys(HOMEMOBILE);
	createContactPage.getTitleTextField().sendKeys(TITLE);
	createContactPage.getOtherPhoneTextField().sendKeys(OTHERPHONE);
	createContactPage.getDepartmentTextField().sendKeys(DEPARTMENT);
	createContactPage.getEmailTextField().sendKeys(EMAIL);
	createContactPage.getFaxTextField().sendKeys(FAX);
	createContactPage.getBirthdateTextField().sendKeys(BIRTHDATE);
	createContactPage.getAssistantTextField().sendKeys(ASSISTANT);
	createContactPage.getAssistancePhoneTextField().sendKeys(ASSISTANTPHONE);
	createContactPage.getSecondaryEmailTextField().sendKeys(SECONDARYEMAIL);
	createContactPage.getEmailoptoutCheckBox().click();
	createContactPage.getReferenceCheckBox().click();
	createContactPage.getNotifyOwnerCheckBox().click();
	createContactPage.getDonotCallCheckBox().click();
	createContactPage.getPortalCheckBox().click();
	createContactPage.getSupportStartDateTextField().clear();
	createContactPage.getSupportStartDateTextField().sendKeys(SUPPORTSTARTDATE);
	createContactPage.getSupportEndDateTextField().clear();
	createContactPage.getSupportEndDateTextField().sendKeys(SUPPORTENDDATE);
	createContactPage.getMailingStreetTextField().sendKeys(MAILINGSTREET);
	createContactPage.getMailingPOBoxTextField().sendKeys(MAILINGPOBOX);
	createContactPage.getMailingCityTextField().sendKeys(MAILINGCITY);
	createContactPage.getMailingStateTextField().sendKeys(MAILINGSTATE);
	createContactPage.getMailingPostalCodeTextField().sendKeys(MAILINGPOSTALCODE);
	createContactPage.getMailingCountryTextField().sendKeys(MAILINGCOUNTRY);
	createContactPage.getOtherStreetTextField().sendKeys(OTHERSTREET);
	createContactPage.getOtherPOBoxTextField().sendKeys(OTHERPOBOX);
	createContactPage.getOtherCityTextField().sendKeys(OTHERCITY);
	createContactPage.getOtherStateTextField().sendKeys(OTHERSTATE);
	createContactPage.getOtherPostalCodeTextField().sendKeys(OTHERPOSTALCODE);
	createContactPage.getOtherCountryTextField().sendKeys(OTHERCOUNTRY);
	//createContactPage.getCopyMailingAddressRadioButton().click();
	createContactPage.getDescriptionTextField().sendKeys(DESCRIPTION);
	createContactPage.getBottonSaveButton().click();
	Thread.sleep(1000);
	Assert.assertEquals(contactPage.getFirstNameView().getText(),FIRSTNAME);
	Thread.sleep(1000);
	Assert.assertEquals(contactPage.getLastNameView().getText(),LASTNAME);
	Thread.sleep(1000);
	contactPage.getDeleteButton().click();
	Thread.sleep(1000);
	webUtil.toHandleJSPopup(driver).accept(); 
	Thread.sleep(1000);
}
}
